# Generated by Django 5.2.5 on 2025-10-12 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliofiles',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='portfolio.portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolioimages',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.portfolio'),
        ),
    ]
